name: Deploy to web8

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm install --legacy-peer-deps

      - run: npx next build

      - name: Deploy to stage
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: web8.boku.net
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          local_path: ./out/*
          remote_path: /stage/
          sftp_only: true

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: web8.boku.net
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          local_path: ./out/*
          remote_path: /site/
          sftp_only: true
